export const REGION_FETCHER_ACTIONS = {
  REGION_DATA_SUCCESS: "REGION_DATA_SUCCESS",
  REGION_DATA_ERROR: "REGION_DATA_ERROR",
  UPATE_REGION: "UPDATE_REGION",
  REGION_SERVICES_DATA_SUCCESS: "REGION_SERVICES_DATA_SUCCESS",
  REGION_SERVICES_DATA_ERROR: "REGION_SERVICES_DATA_ERROR"
};
